GovAlta/dcp-monorepo

.github/workflows/pipeline.yml
.github/workflows/pull-request.yml
.openshift/environment.infra.yml
.openshift/environments.yml
apps/dcp-guide/src/pages/index.astro
libs/dcp-common/README.md
libs/dcp-common/project.json
libs/dcp-common/src/env.d.ts
libs/dcp-common/src/index.js
libs/dcp-common/src/lib/DcpCommon.astro
libs/dcp-common/src/lib/layouts/DefaultMicrositeLayout.astro
libs/dcp-common/tsconfig.json
tsconfig.base.json

Also correcting build project in manifests.

chore: adding a lib as a reference for shared layouts and components

---

apps/common-capabilities/src/pages/index.astro

This is a test checkin to ensure that we can push changes to lower regions

Changed wording to microsite

---

apps/common-capabilities/README.md

Added a readme file for Common capabilities

Create README.md for Common Capabilities

---

apps/common-capabilities/src/components/Header.tsx
apps/common-capabilities/src/content/datastore.json

1. Changed the header to "Building blocks for your custom apps"
2. Added more context to Shared services from Justice Digital team

Made minor content changes

---

apps/common-capabilities/src/components/Card/styles.css
apps/common-capabilities/src/components/ExternalLink/styles.css
apps/common-capabilities/src/content/datastore.json
apps/common-capabilities/src/pages/contact/faq.json
apps/common-capabilities/src/pages/contact/index.tsx
apps/common-capabilities/src/pages/contact/styles.css
apps/common-capabilities/src/pages/details/index.tsx
apps/common-capabilities/src/pages/details/styles.css
apps/common-capabilities/src/pages/home/styles.css

CC: contact page and css fixes

---

apps/common-capabilities/src/components/Header.tsx
apps/common-capabilities/src/pages/home/index.tsx
apps/common-capabilities/src/pages/home/styles.css

CC: Added last updated message to the home page

---

apps/common-capabilities/src/components/Card/index.tsx
apps/common-capabilities/src/components/ExternalLink/index.tsx
apps/common-capabilities/src/content/datastore.json
apps/common-capabilities/src/layouts/Layout.astro
apps/common-capabilities/src/pages/[slug].astro
apps/common-capabilities/src/pages/contact/index.tsx
apps/common-capabilities/src/pages/details/index.tsx
apps/common-capabilities/src/pages/details/styles.css
apps/common-capabilities/src/pages/home/index.tsx
apps/common-capabilities/src/pages/home/styles.css
apps/common-capabilities/src/pages/home/utils.js

https://github.com/GovAlta/dcp-monorepo/assets/31360331/a0ec583a-91b0-4b0a-8aa2-7cb5693323cd

CC: filter services

---

apps/common-capabilities/src/components/Card/index.tsx

Changed the word length to 200 to account for few description on getting truncated

Changed the word length to 200 to account for few description

---

apps/common-capabilities/src/pages/contact/faq.json

The part added is "It's important to note that while we offer a listing and information for these common capabilities, we are not the owners of these capabilities. For specific inquiries, we recommend reaching out to the respective teams."

Updated the wordings in FAQ

---

apps/common-capabilities/src/pages/home/config.ts
apps/common-capabilities/src/pages/home/index.tsx
apps/common-capabilities/src/pages/home/utils.js

https://github.com/GovAlta/dcp-monorepo/assets/31360331/0eba7460-6c63-4bd9-b9da-3b2592d4f128

CC: Added collapsible fields for filters

---

apps/common-capabilities/src/components/Card/index.tsx
apps/common-capabilities/src/pages/home/index.tsx
apps/common-capabilities/src/pages/home/styles.css

https://github.com/GovAlta/dcp-monorepo/assets/31360331/e2d57139-d3cf-400f-b019-84ab02dce12c

CC: Added a new section for recommended services based on weightage

---

apps/common-capabilities/src/content/datastore.json
apps/common-capabilities/src/pages/contact/index.tsx
apps/common-capabilities/src/pages/contact/styles.css
apps/common-capabilities/src/pages/details/index.tsx
apps/common-capabilities/src/pages/home/config.ts
apps/common-capabilities/src/pages/home/index.tsx

CC: Bug fix and enhancements

---

apps/common-capabilities/src/pages/landing/index.tsx

Added the content below 
- Accelerate development by reusing existing capabilities and build new services faster.
- Enhance security and compliance measures to create ethical services that protect user privacy.
- Contribute to a culture of collaboration across teams to ensure service delivery efficiency and innovation.

Changed content to match the final prototype

---

apps/common-capabilities/src/pages/ecosystem/config.ts

Updating the Ecosystem page - moved teams to right org

---

apps/common-capabilities/data/CSV2JSON.py
apps/common-capabilities/data/CommonCapabilitiesFields.csv
apps/common-capabilities/src/pages/details/config.ts
apps/common-capabilities/src/pages/details/index.tsx

Security group headers. Do not show specifications that were defaulted to "Other", + minor code clean-up

Minor fixes:

---

apps/common-capabilities/src/components/Card/index.tsx
apps/common-capabilities/src/pages/services/index.tsx

Pages changes as per Figma - for further refinements

---

apps/common-capabilities/src/pages/details/index.tsx

Added contact details

---

apps/common-capabilities/src/pages/details/index.tsx
apps/common-capabilities/src/pages/landing/index.tsx

Also includes CC-240. Changed code to match official name of GitHub

changed maxContentWidth from 1500px to 1200px

---

apps/digital-standards/src/components/Header.tsx
apps/digital-standards/src/pages/landing/index.tsx

Made changes to the top right hand site menu. Also made a few grammar edits.

Site Navigation changes and small grammar changes

---

apps/common-capabilities/src/components/Header.tsx
apps/common-capabilities/src/layouts/Layout.astro

Added feedback widget to common capabilities

---

apps/common-capabilities/src/layouts/Layout.astro
apps/common-capabilities/src/layouts/layout/index.tsx
apps/common-capabilities/src/pages/[slug].astro
apps/common-capabilities/src/pages/about.astro
apps/common-capabilities/src/pages/ecosystem.astro
apps/common-capabilities/src/pages/gettingstarted.astro
apps/common-capabilities/src/pages/index.astro
apps/common-capabilities/src/pages/services.astro
apps/common-capabilities/src/pages/support.astro
apps/digital-standards/src/layouts/Layout.astro

fix: added client:only directive at root level for CC and DS app!

---

apps/digital-marketplace/public/forms.js

The api will be called regardless of the status of the agree checkbox. This was for development purposes.

Submit develop mode was removed

---

apps/digital-marketplace/public/domain_exports.js
apps/digital-marketplace/public/forms.js
apps/digital-marketplace/src/pages/for-suppliers.astro

Added UAT testing options on supplier page to allow error testing.

added promise to submitForm. UAT testing options on supplier page
